INSERT INTO public.comarques (nom_c,provincia) VALUES
      ('Safor','València'),
      ('Horta Sud','València'),
      ('Camp de Morvedre','València'),
      ('Foia de Bunyol','València'),
      ('Alacantí','Alacant'),
      ('Alt Maestrat','Castelló'),
      ('Plana Baixa','Castelló'),
      ('Horta Nord','València'),
      ('Ports','Castelló'),
      ('Racó','València'),
      ('Plana d''Utiel','València'),
      ('Vinalopó Mitjà','Alacant'),
      ('Vall de Cofrents','València'),
      ('Alt Vinalopó','Alacant'),
      ('Ribera Baixa','València'),
      ('Baix Segura','Alacant'),
      ('Ribera Alta','València'),
      ('Marina Alta','Alacant'),
      ('Serrans','València'),
      ('Costera','València'),
      ('València','València'),
      ('Baix Maestrat','Castelló'),
      ('Marina Baixa','Alacant'),
      ('Vall d''Albaida','València'),
      ('Alcoià','Alacant'),
      ('Canal de Navarrés','València'),
      ('Horta Oest','València'),
      ('Camp de Túria','València'),
      ('Alt Millars','Castelló'),
      ('Alcalatén','Castelló'),
      ('Baix Vinalopó','Alacant'),
      ('Comtat','Alacant'),
      ('Alt Palància','Castelló'),
      ('Plana Alta','Castelló');